apiVersion: v1
kind: Service
metadata:
  name: replace_release_name-health
  namespace: replace_namespace
spec:
  ports:
    - name: http
      port: 14269
      protocol: TCP
      targetPort: 14269
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: replace_release_name
    app.kubernetes.io/name: replace_release_name
    app.kubernetes.io/part-of: jaeger
  type: ClusterIP
