apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: keycloak-jwt
spec:
  name: keycloak-jwt
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin-svc.replace_namespace.svc:8000
    listen_path: /keycloak-jwt
    strip_listen_path: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: replace_realm_url/protocol/openid-connect/certs
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - replace_namespace/keycloak-jwt
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-jwt
spec:
  name: keycloak-jwt
  state: active
  active: true
  access_rights_array:
    - name: keycloak-jwt
      namespace: replace_namespace
      versions:
        - Default
