---
apiVersion: tyk.tyk.io/v1alpha1
kind: SubGraph
metadata:
  name: users-subgraph
spec:
  schema: |
    directive @extends on OBJECT | INTERFACE

    directive @external on FIELD_DEFINITION

    directive @key(fields: _FieldSet!) on OBJECT | INTERFACE

    directive @provides(fields: _FieldSet!) on FIELD_DEFINITION

    directive @requires(fields: _FieldSet!) on FIELD_DEFINITION

    type Address {
      street: String!
      suite: String!
      city: String!
      zipcode: String!
      geo: GeoLocation!
    }

    type Company {
      name: String!
      catchPhrase: String!
      bs: String!
    }

    type Entity {
      findUserByID(id: ID!): User!
    }

    type GeoLocation {
      lat: String!
      lng: String!
    }

    type Query {
      user(id: ID!): User!
      users: [User!]!
      _entities(representations: [_Any!]!): [_Entity]!
      _service: _Service!
    }

    type User {
      id: ID!
      name: String!
      username: String!
      email: String!
      address: Address!
      phone: String!
      website: String!
      company: Company!
    }

    scalar _Any

    union _Entity = User

    scalar _FieldSet

    type _Service {
      sdl: String
    }
  sdl: |
    extend type Query {
        user(id: ID!): User!
        users: [User!]!
    }

    type User @key(fields: "id") {
        id: ID!
        name: String!
        username: String!
        email: String!
        address: Address!
        phone: String!
        website: String!
        company: Company!
    }

    type Address {
        street: String!
        suite: String!
        city: String!
        zipcode: String!
        geo: GeoLocation!
    }

    type GeoLocation {
        lat: String!
        lng: String!
    }

    type Company {
        name: String!
        catchPhrase: String!
        bs: String!
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: users-subgraph
spec:
  name: users-subgraph
  protocol: http
  active: true
  internal: true
  use_keyless: true
  graphql:
    enabled: true
    execution_mode: subgraph
    graph_ref: users-subgraph
    version: "2"
    playground:
      enabled: false
      path: ""
  proxy:
    target_url: http://replace_service_url/query
    listen_path: /users-subgraph/
    disable_strip_slash: true
    strip_listen_path: true
